[tox]
downloadcache = {toxworkdir}/cache/
envlist =
    py313,

[testenv]
passenv = DATABASE_URL
basepython =
    py313: python3.13
commands =
    python -m tldap.test.slapd ./run_tests.sh
deps =
    cracklib
    -rrequirements/tests.txt
