# Generated by Django 2.2.10 on 2020-02-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kgapplications", "0008_auto_20190605_0827"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="existing_person",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="new_applicant",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="kgapplications.Applicant"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
