# Generated by Django 2.2.10 on 2020-02-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kgapplications", "0010_applicants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="application",
            name="object_id",
        ),
    ]
