# Generated by Django 4.2.5 on 2023-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kgapplications", "0011_auto_20200228_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="rcao",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="RCAO Email"),
        ),
    ]
