#!/bin/bash

# File needs to be called /hooks/build relative to the Dockerfile.
# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Building slurm 16.05"
docker build \
    --tag "$DOCKER_REPO:16.05" \
    --build-arg="SLURM_VER=16.05.10" \
    --build-arg="SLURM_URL=https://www.schedmd.com/downloads/archive/slurm-16.05.10.tar.bz2" \
    .

echo "Building slurm 17.02"
docker build \
    --tag "$DOCKER_REPO:17.02" \
    --build-arg="SLURM_VER=17.02.7" \
    --build-arg="https://www.schedmd.com/downloads/latest/slurm-17.02.7.tar.bz2" \
    .
