#!/usr/bin/env python

import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'karaage.conf.settings'

from django.core import management

if __name__ == "__main__":
    management.call_command('clearsessions')
    management.call_command('lock_expired')
    management.call_command('clear_usage_cache')
    management.call_command('clear_usage_graphs')
    management.call_command('application_cleanup')
    management.call_command('link_software', all=True)
