#!/bin/sh

set -ex

TMPDIR=$(mktemp -d)
trap "rm -rf -- '$TMPDIR'" EXIT HUP INT TERM

virtualenv --system-site-packages "$TMPDIR"
. "$TMPDIR/bin/activate"

pip install django==1.6.5
pip install south

if test -x /usr/share/python-karaage/bin/kg-manage
then
    /usr/share/python-karaage/bin/kg-manage migrate --all "$@"
else
    kg-manage migrate --all "$@"
fi

touch /etc/karaage3/south_migrations_complete
