#!/bin/sh
set -ex

TMPDIR=$(mktemp -d)
trap "rm -rf -- '$TMPDIR'" EXIT HUP INT TERM

virtualenv --system-site-packages "$TMPDIR"
. "$TMPDIR/bin/activate"

pip install django==1.6.10
pip install south

CMD="$(command -v kg-manage)"
python "$CMD" migrate "$@"
