#!/usr/bin/python
import os
import re
from random import choice

main_settings_file = "/etc/karaage/global_settings.py"
main_settings_file_tmp = "/etc/karaage/global_settings.py.tmp"

settings_contents = open(main_settings_file, 'r').read()
secret_key = ''.join([choice('abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for i in range(50)])
settings_contents = re.sub(r"(?<=SECRET_KEY = ')'", secret_key + "'", settings_contents)

fp = open(main_settings_file_tmp, 'w')
fp.write(settings_contents)
fp.close()

os.rename(main_settings_file_tmp, main_settings_file)
