#!/bin/sh -e

if [ "$1" = "purge" ]
then
    for i in /var/log/karaage \
             /var/cache/karaage/graphs \
             /var/cache/karaage/matplotlib
             /var/log/karaage3 \
             /var/cache/karaage3/graphs \
             /var/cache/karaage3/matplotlib
    do
        if dpkg-statoverride --list $i >/dev/null 2>&1
        then
            dpkg-statoverride --remove $i
            rm -rf $i
        fi
    done
fi

#DEBHELPER#
