#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
    
    # The following only on a new install
    if [ "$2" = "" ]; then
	
	/usr/sbin/kg_set_secret_key
	
    fi

    for i in /var/cache/karaage/graphs/projects \
             /var/cache/karaage/graphs/institutes \
             /var/cache/karaage/graphs/i_trends \
             /var/cache/karaage/graphs/trends \
             /var/cache/karaage/graphs/machines \
             /var/www/.kgmatplotlib
    do
        # only do something when no setting exists
        if ! dpkg-statoverride --list $i >/dev/null 2>&1
        then
            dpkg-statoverride --update --add root www-data 2775 $i
        fi
    done
fi

#DEBHELPER#

update-python-modules -p karaage.public

if [ -x /usr/sbin/kg-manage ]
then
    if /usr/sbin/kg-manage migrate --list | grep -q "( )"
    then
        db_input high karaage/run_migrations || true
        db_go
        
        db_get karaage/run_migrations
        if [ "$RET" = "false" ]; then
            db_input high karaage/no_migrations || true
            db_go
        fi
    fi
fi


if [ -x /usr/sbin/kg-manage ]
then
    if /usr/sbin/kg-manage migrate --list | grep -q "( )"
    then     
        db_get karaage/run_migrations
        if [ "$RET" = "true" ]; then
            echo "Running migrations"
            /usr/sbin/kg-manage migrate
        fi
    fi
fi
db_fset karaage/run_migrations seen "false"


exit 0

