#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ "$1" = "configure" ]; then
    
    # The following only on a new install
    if [ "$2" = "" ]; then
	
	/usr/sbin/kg_set_secret_key
	
    fi
fi

#DEBHELPER#

update-python-modules -p karaage.public

db_get karaage/run_migrations
if [ "$RET" = "true" ]; then
    dpkg-trigger karaage-migrations
fi
db_reset karaage/run_migrations


exit 0

