#!/bin/sh -e

if [ "$1" = "purge" ]
then
    for i in /var/cache/karaage/graphs/projects \
             /var/cache/karaage/graphs/institutes \
             /var/cache/karaage/graphs/i_trends \
             /var/cache/karaage/graphs/trends \
             /var/cache/karaage/graphs/machines \
             /var/cache/karaage/matplotlib
    do
        if dpkg-statoverride --list $i >/dev/null 2>&1
        then
            dpkg-statoverride --remove $i
            rm -rf $i
        fi
    done
fi

#DEBHELPER#
