# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaage', '0003_auto_20150410_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='delegates',
            field=models.ManyToManyField(blank=True, related_name='delegate_for', through='karaage.InstituteDelegate', to=settings.AUTH_USER_MODEL),
        ),
    ]
