# Generated by Django 4.2.6 on 2023-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karaage", "0008_institute_saml_scoped_affiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_notified_pending_expiration",
            field=models.BooleanField(default=False),
        ),
    ]
