# Generated by Django 4.2.6 on 2023-11-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karaage", "0009_project_has_notified_pending_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rcao",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="RCAO Email"),
        ),
    ]
