# Generated by Django 4.2.6 on 2023-11-01 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karaage", "0012_project_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institute",
            name="project_prefix",
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator("^[a-zA-Z]{4}$")]),
        ),
    ]
